biset/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'testDjango.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^profile/', include('userprofile.urls',namespace="userprofile")),
    url(r'^$', include('home.urls', namespace="home")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^datasets/', include('dataset.urls', namespace="datasets")),
    url(r'^myturk/', include('myturk.urls', namespace="myturk")),
    url(r'^wiki/', include('wiki.urls', namespace="wiki")),
    url(r'^datamng/', include('datamng.urls', namespace="datamng")),
    url(r'^vis/', include('vis.urls', namespace="vis")),
    url(r'^home/', include('home.urls', namespace="home")),
	
) + staticfiles_urlpatterns()

projects/urls.py
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from projects import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^(?P<project_id>\d+)/$', views.detail, name='detail'),
    url(r'^add/$', views.add, name='add'),
    url(r'^plist/$', views.plist, name='plist'),
    url(r'^edit/(?P<project_id>\d+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<project_id>\d+)/$', views.delete, name='delete'),
    url(r'^undo_delete/(?P<project_id>\d+)/$', views.undo_delete, name='undo_delete'),
    url(r'^undo_project_delete/(?P<project_id>\d+)/(?P<log_id>\d+)/$', views.undo_project_delete, name='undo_project_delete'),
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    #url(r'^(?P<project_id>\d+)/comment/$', views.comment, name='comment'),
    url(r'^comment/delete/$', views.delete_comment, name='delete_comment'), 
    url(r'^undo_comment_delete/(?P<comment_id>\d+)/(?P<log_id>\d+)/$', views.undo_comment_delete, name='undo_comment_delete'),
    url(r'^comment/save/$', views.save_comment, name='save_comment'),  
    url(r'^sort_comment_asc/(?P<project_id>\d+)/$', views.sort_comment_asc, name='sort_comment_asc'), 
    url(r'^sort_comment_desc/(?P<project_id>\d+)/$', views.sort_comment_desc, name='sort_comment_desc'), 
    url(r'^collaborator/add/$', views.add_collaborator, name='add_collaborator'), 
    url(r'^collaborator/delete/$', views.delete_collaborator, name='delete_collaborator'), 
    url(r'^test/$', views.load_project_activity_feed, name='test'),   
    url(r'^userlist/$', views.get_user_list, name='userlist'),   
)

userprofile/urls.py
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from userprofile import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^(?P<user_id>\d+)/$', views.view_profile, name='view_profile'),
    url(r'^edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
)

vis/urls.py
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from vis import views

urlpatterns = patterns('',
    # ex: /polls/
    # url(r'^$', views.index, name='index'),
    url(r'^loadbisets/$', views.getVisJson, name='loadBisets'),
    url(r'^analytics/$', views.analytics, name='analytics'),
    url(r'^loadVis/$', views.loadVis, name='loadVis'),
    url(r'^saveVis/$', views.saveVis, name='saveVis'),
    url(r'^deleteVis/$', views.deleteVis, name='deleteVis'),
    url(r'^addVis/$', views.addVisConfig, name='addVisConfig'),
    url(r'^loadVisList/$', views.loadVisList, name='loadVisList'),
)

userprofile/models.py
# Django
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save


class UserProfile(models.Model):
    CAREER_CHOICES = (
        ('F', 'Falcuty'),
        ('U', 'Under Graduate'),
        ('G', 'Graduate'),
        ('O', 'Others')
    )
    user        = models.OneToOneField(User)
    location = models.CharField(max_length=100)
    career = models.CharField(max_length=1, choices = CAREER_CHOICES)
    
    def __unicode__(self):
        return self.user.username

userprofile/views.py
# Django
from django.http import HttpResponse, Http404
from django.shortcuts import render_to_response #render
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required
from userprofile.models import UserProfile
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.conf import settings
from django.template.response import TemplateResponse
from home.utils import * 
from types import *
import json
from django.contrib.auth.hashers import check_password, make_password

@login_required
def view_profile(request, user_id):
    '''
    Display a user's profile. If user_id if provided, then the user 
    will be the user of the user id. Otherwise, the user will be the
    login user.
    @param request: Django http request
    @param user_id: the id of a user
    '''
    
    thisuser = User.objects.get(pk = user_id)
    
    if thisuser == request.user:
        perm = True
    else:
        perm = False
    
    try:        
        from django.contrib.admin.models import LogEntry
        
        new_logging_list = []
        # Dispay the logActions only when "this user" is the loggin user. 
        if thisuser == request.user:
            hist_actions = LogEntry.objects.filter(user = request.user)
            actions_list = list(hist_actions)           
            action_dict = { '1' : "add", '2' : 'update', '3' : 'delete'}
            
            # rebuild the logging list
            for item in actions_list:
                logContentType = item.content_type 
                logAction = item.action_flag
                logObject = None
                targetObject = None
                
                try:    
                    logObject = logContentType.get_object_for_this_type(pk=item.object_id)
                except Exception as e:
                    logObject = None                
                
                logAction = action_dict[str(logAction)]
                
                new_logging_list.append({      
                    'id':item.id,
                    'action_time':item.action_time, 
                    'change_message':item.change_message, 
                    'logObject':logObject, 
                    'logAction' : logAction,
                    'logContentType': logContentType.name})

        profile = thisuser.userprofile
        
                
        context = { "profile":profile, "this_user":thisuser, 'active_tag': 'userprofile', 
            'BASE_URL':settings.BASE_URL, 'history_actions': new_logging_list, 'perm':perm}
        return TemplateResponse(request, 'userprofile/view_profile.html', context) 
    except Exception as e:
        return HttpResponse(e)

@login_required
def edit_profile(request):
    '''
    Updating user profile.
    @param request: Django http request
    '''
    if request.method == 'POST':
        try:
            requestJson = json.loads(request.body)
            # print requestJson
            uid = requestJson['user_id']
            
            profile_user = User.objects.get(pk = uid);
            if not profile_user == request.user:
                raise Http404
            
            theProfile = UserProfile.objects.get(user = uid)
            theUser = theProfile.user
            
            theUser.first_name = requestJson['first_name']
            theUser.last_name = requestJson['last_name']
            theUser.email = requestJson['email']
            theUser.save()
            
            theProfile.location = requestJson['location']            
            theProfile.career = requestJson['career']
            theProfile.save()
            
            return HttpResponse(json.dumps({'status':'success'}), content_type = "application/json")
            
        except Exception as e:
            print e
    else:
        raise Http404
        
@login_required
def change_password(request):
    '''
    Handing password change request.
    @param request: Django http request
    '''
    if request.method == 'GET':
        context = { 'active_tag': 'profile', 'BASE_URL':settings.BASE_URL}
        return TemplateResponse(request, 'userprofile/change_pass.html', context)
    elif request.method == 'POST':
        requestJson = json.loads(request.body)
        theUser = request.user
        current_password = requestJson['current_password']
        new_password = requestJson['new_password']
        repeat_password = requestJson['repeat_password']
        
        if not check_password(current_password, theUser.password): 
            return HttpResponse(json.dumps({'status':'password_incorrect'}), content_type = "application/json")
           
        if not new_password == repeat_password:
            return HttpResponse(json.dumps({'status':'repeat_password_incorrect'}), content_type = "application/json")

         
        theUser.password = make_password(new_password)
        theUser.save()
        
        return HttpResponse(json.dumps({'status':'success'}), content_type = "application/json")        
    else:
        raise Http404   

templates/userprofile/base.html
{% load admin_static %}{% load firstof from future %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
<script type="text/javascript">window.__admin_utc_offset__ = "{% filter escapejs %}{% now "Z" %}{% endfilter %}";</script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% if user.is_active and user.is_staff %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% url 'django-admindocs-docroot' as docsroot %}
                {% if docsroot %}
                    <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

templates/userprofile/change_pass.html
{% extends "projects/base.html" %}
{% load staticfiles %}

{% load i18n %}
{% block content %}
		<h1>Change Password</h1>
		<hr>
		<div class="col-md-12">
            <div class="panel panel-default widget shade-container">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-user"></span>
                    <h3 class="panel-title">Change Password</h3>
                </div>
                <div class="panel-body">
                <label style = "display:none;" id = 'userid'>{{ user.id }}</label>
                <!-- edit form column -->                    
			        <div class="col-md-8 col-md-offset-3 ">
			            <div class="form-horizontal">
                        <input id="csrf_token" type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
			                <div class="form-group" style = "margin-top:10px">
			                    <label class="col-lg-4 control-label">Current password:</label>
			                    <div class="col-lg-8">
	            					<input type="text" name="oldPass" placeholder="Old Password" id="old_password"><br/>											                        
			                    </div>
			                </div>
                            
                            <div class="form-group">
			                    <label class="col-lg-4 control-label">New password:</label>
			                    <div class="col-lg-8">
	            					<input type="text" name="newPass" placeholder="New Password" id="new_password"><br/>											                        
			                    </div>
			                </div>
                            
                            <div class="form-group">
			                    <label class="col-lg-4 control-label">Repeat new password:</label>
			                    <div class="col-lg-8">
	            					<input type="text" name="repeatPass" placeholder="Repeat Password" id="repeat_password"><br/>											                        
			                    </div>
			                </div>

			                <div class="form-group">
			                    <div class="col-md-12">
			                        <div class="col-md-3"></div>
			                        <div class="col-md-9">
                                        <div class="col-md-3">
                                            <button type="button" class="btn btn-info btn-x active_this" id="btn_change_pass_save"><span class="glyphicon glyphicon-lock"></span> Save Changes</button>
                                        </div>
										<div class="col-md-3">
											<button type="button" class="btn btn-default btn-x" id="btn_change_pass_cancel">Cancel</button>
		                        		</div>
										
<!-- 										<div class="col-md-4 col-md-offset-4">
		                        		<button type="button" class="btn btn-info btn-xs" id="btn_edit"><span class="glyphicon glyphicon-lock"></span> Change Password</button>											
										</div> -->		                        		
			                        </div>
			                    </div>
			                </div>
			            </div>
			        </div>
                </div>
            </div>			
		</div>       
		

		
    
    
	<script type="text/javascript" src="{% static 'profile/js/edit.js'%}"></script>
{% endblock %}

templates/userprofile/view_profile.html
{% extends "projects/base.html" %}
{% load staticfiles %}

{% load i18n %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo;
</div>

first name: {{ user.firstname }}
{% endblock %}
{% endif %}

{% block sidebar %}{% endblock %}

{% block content %}
		<h1>{% if perm == True %} My {% else %} {{ this_user.first_name }} {{ this_user.last_name }}'s {% endif %} profile</h1>
		<hr>
		<div class="col-md-8">
            <div class="panel panel-default widget shade-container">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-user"></span>
                    <h3 class="panel-title">{% if perm == True %} My {% else %} {{ this_user.first_name }} {{ this_user.last_name }}'s {% endif %} profile</h3>
                </div>

                <div class="panel-body" id="uprofile_info">
					<!-- left column -->
			        <div class="col-md-4 col-sm-6 col-xs-12">
			            <div class="text-center" id="uprofile_img">
			                <img src="{% static 'common/imgs/default.jpg' %}" class="avatar img-circle img-thumbnail" alt="avatar">
			            </div>
			        </div>

			        <!-- edit form column -->
			        <div class="col-md-8 col-md-offset-0 col-sm-6 col-xs-12">
			            <div class="form-horizontal">
                        <input id="csrf_token" type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
			                <div class="form-group">
			                    <label class="col-md-3 control-label">Username:</label>
                                <label style = "display:none;" id = 'userid'>{{ this_user.id }}</label>
			                    <div class="col-md-8">
			                        <p class="p_aligh_lable" id = 'username'>{{ this_user.username }}</p>
			                    </div>
			                </div>

			                <div class="form-group">
			                    <label class="col-lg-3 control-label">First name:</label>
			                    <div class="col-lg-8">
			                        <p class="p_aligh_lable active_this" id="profile_first_name">{{ this_user.first_name }}</p>
	            					<div class="hide_this">
										<input type="text" name="firstName" placeholder="First Name" id="edit_first_name" data-toggle="tooltip"><br />
									</div>			                        
			                    </div>
			                </div>

			                <div class="form-group">
			                    <label class="col-lg-3 control-label">Last name:</label>
			                    <div class="col-lg-8">
			                        <p class="p_aligh_lable active_this" id="profile_last_name">{{ this_user.last_name }}</p>
	            					<div class="hide_this">
										<input type="text" name="lastName" placeholder="Last Name" id="edit_last_name" data-toggle="tooltip"><br />
									</div>			                        
			                    </div>
			                </div>

			                <div class="form-group">
			                    <label class="col-lg-3 control-label">Email:</label>
			                    <div class="col-lg-8">
			                        <p class="p_aligh_lable active_this" id="profile_email">{{ this_user.email }}</p>
	            					<div class="hide_this">
										<input type="text" name="email" placeholder="Email" id="edit_email" data-toggle="tooltip"><br />
									</div>			                        
			                    </div>
			                </div>

			                <div class="form-group">
			                    <label class="col-lg-3 control-label">Career:</label>
			                    <div class="col-lg-8" id="uprofile_career">
									<p class="p_aligh_lable active_this">
	                                    {% for item in profile.CAREER_CHOICES %}
	                                        {% if profile.career = item.0 %} {{item.1}} {% endif%} 
	                                    {% endfor %}
									</p>
			                    </div>

			                    <div class="col-lg-8 hide_this" id="uprofile_career_sel">
			                        <select id="id_career" name="career" style = "margin-top:5px">
                                    {% for item in profile.CAREER_CHOICES %}   
                                        <option value="{{item.0}}" {% if profile.career = item.0 %} selected{% endif%}>{{item.1}}</option>
                                    {% endfor %}
                                    </select>
			                    </div>
			                </div>

			                <div class="form-group">
			                    <label class="col-lg-3 control-label">Location:</label>
			                    <div class="col-lg-8">
			                        <p class="p_aligh_lable active_this" id="profile_location">{{ profile.location }}</p>
	            					<div class="hide_this">
										<input type="text" name="location" placeholder="Location" id="edit_location" data-toggle="tooltip"><br />
									</div>			                        
			                    </div>
			                </div>

			                <div class="form-group">
			                    <div class="col-md-12">
			                        <div class="col-md-5"></div>
			                        <div class="col-md-5">
                                        {% if perm == True %}
			                        	<div class="col-md-7">
		                        			<button type="button" class="btn btn-info btn-xs active_this" id="btn_profile_edit"><span class="glyphicon glyphicon-pencil"></span> Edit Profile</button>
											<button type="button" class="btn btn-success btn-xs hide_this" id="btn_profile_save"><span class="glyphicon glyphicon-ok"></span> save</button>
										</div>
                                        <div class="col-md-5">
                                            <button type="button" class="btn btn-info btn-xs active_this" id="btn_change_pass"><span class="glyphicon glyphicon-lock"></span> Change Password</button>
                                        </div>
										<div class="col-md-5">
											<button type="button" class="btn btn-default btn-xs hide_this" id="btn_profile_cancel">Cancel</button>
		                        		</div>
										{% endif %}
		                        		
			                        </div>
			                    </div>
			                </div>
			            </div>
			        </div>
                </div>
            </div>			
		</div>       
		
		<div class="col-md-4 col-md-offset-0 {% if perm == False %} hide_this {% endif %}">
            <!-- collaborator of a project -->
            <div class="panel panel-default widget shade-container">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-list-alt"></span>
                    <h3 class="panel-title">My Recent Activities</h3>
                    <span class="label label-info">{{history_actions|length}}</span>
                </div>
                <div class="panel-body" id="uprofile_activity">
                    <ul class="list-group">
				        {% for item in history_actions%}
				        	<li class="list-group-item">
                            	<div class="row">
	                                <div class="col-xs-4 col-md-2 left_15_gap">
                                    	<img src="{% static 'common/imgs/default.jpg' %}" class="img-circle img-responsive" alt="" />
                                	</div>
                                	<div class="col-xs-7 col-md-9">
                                		<p>
                                		{{ item.logAction }} 
                                        {% if item.logContentType == 'comment' %}
                                            a comment
                                            To project 
                                            {% if item.logObject.project.is_deleted %}
                                                    '{{ item.logObject.project }}'
                                                {% else %}
                                                    <a href = '{% url 'projects:detail' item.logObject.project.pk %}'>{{ item.logObject.project }}</a> 
                                                {% endif %} 
                                        {% elif  item.logContentType == 'collaborationship'%}
                                            a collaborator                                        
                                            {% if item.logObject != None %}
                                                at 
                                                {% if item.logObject.project.is_deleted %}
                                                    '{{ item.logObject.project }}'
                                                {% else %}
                                                    <a href = '{% url 'projects:detail' item.logObject.project.pk %}'>{{ item.logObject.project }}</a> 
                                                {% endif %}    
                                            {% endif %}
                                        {% elif item.logContentType == 'project'%}    
                                           project                
                                           {% if item.logObject.is_deleted and item.logAction = 'delete'%}
                                                <!-- '{{ item.logObject.name}}' <a href = '{% url 'projects:undo_delete' item.logObject.pk %}'>Undo?</a>-->
                                                '{{ item.logObject.name}}' <a href = '{{BASE_URL}}projects/undo_project_delete/{{item.logObject.pk}}/{{item.id}}/'>(Undo?)</a>
                                           {% else %}
                                                <a href = '{% url 'projects:detail' item.logObject.pk %}'>{{ item.logObject.name}}</a>
                                           {% endif %}
                                        
                                        {% endif %}
                                            
							            {% if item.change_message != '' %}
                                           , {{ item.change_message }}        
							            {% endif %}
                                		</p>
                                		<div class="mic-info">On {{ item.action_time }}</div>
                                	</div>
                            	</div>
                        	</li>                        	
				        {% endfor %}
						                        				        
                    </ul>
                    <!-- placeholder for more activities -->
                    <!-- <a href="#" class="btn btn-info btn-sm btn-block" role="button"><span class="glyphicon glyphicon-refresh"></span> More</a> -->
                </div>
            </div>			
		</div>
    </div>
    
    
	<script type="text/javascript" src="{% static 'profile/js/edit.js'%}"></script>
{% endblock %}